# Generated by Django 4.2.5 on 2023-09-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_enrolled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-total_enrolled'], name='courses_cou_total_e_7b3798_idx'),
        ),
    ]
